import { solveDay6 } from "./day6";

describe("Day 6", () => {
  it("should solve example input correctly", () => {
    const exampleInput = `
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
......X.#.
#.........
......#...`;
    expect(solveDay6(exampleInput)).toBe(41);
  });
});
